### ISSUE TITLE
Docs issues

### ISSUE THREAD

**Issue by halil3d** [shotgunsoftware/tk-multi-bg-publish#3]
On the page:
[Docs » How it works with tk-multi-publish2](https://developer.shotgridsoftware.com/tk-multi-bg-publish/works_with_publish2.html)

The following diagram is not available for view when clicked:
https://developer.shotgridsoftware.com/tk-multi-bg-publish/resources/batch_publishing_overview.png

![image](https://user-images.githubusercontent.com/17039888/196323502-e1f256c0-cb8a-46e4-8bd9-1e2389ac9723.png)

Also on the page:
[Docs » Monitor UI and logs](https://developer.shotgridsoftware.com/tk-multi-bg-publish/monitor_and_logs.html)

The user docs link is returning "This site can’t be reached" error in the browser.
https://help-staging.autodesk.com/view/ALIAS/2023/ENU/?guid=Alias_ShotGrid_Workflows_alias_shotgrid_publishing_html#Background%20publishing

**Comment by rob-aitchison** [comment]
Hello @halil3d ,
Thanks for logging this issue and apologies it took some time for us to log it. We now have it in the backlog and will address it as soon as possible, thank you again!

**Comment by rob-aitchison** [comment]
The broken graphic link should now be fixed. The user docs link still needs updating.

**Comment by rob-aitchison** [comment]
We are now pointing at live docs in the SG tree instead of the Alias tree. One anchor point request to go to complete the update.

**Comment by rob-aitchison** [comment]
All issues should be addressed now, please open a new issue if one is discovered. Thanks again for taking the time to point this out to us!
